WebAPITutorial/Models/ErrorViewModel.cs
using System;

namespace WebAPITutorial.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAPITutorial/Models/Heroes/Hero.cs
using System.ComponentModel.DataAnnotations;

namespace WebAPITutorial.Models.Heroes
{
	public class Hero
    {
		public int ID
		{
			get;set;
		}
		[Display(Name="Hero Name")] // this allows the Name property's display text to be "Hero Name"
		//[DataType(DataType.Passowrd)] Allows the Property to be a password-like input.
		[Required, MaxLength(50)]
		public string Name
		{
			get;set;
		}
		public string DOB
		{
			get;set;
		}
		public string Power
		{
			get;set;
		}
		public HeroType Type
		{
			get; set;
		}
	}
}

WebAPITutorial/Models/Heroes/HeroEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAPITutorial.Models.Heroes
{
    public class HeroEditModel
    {
		[Required, MaxLength(50)]
		public string Name
		{
			get; set;
		}
		[Required]
		public HeroType Type
		{
			get; set;
		}
		public string DOB
		{
			get; set;
		}
		public string Power
		{
			get; set;
		}
		public int ID
		{
			get; set;
		}
	}
}

WebAPITutorial/Models/Heroes/HeroType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAPITutorial.Models.Heroes
{
    public enum HeroType
    {
		None,
		Strength,
		Immortality,
		Science,
		Skills
    }
}

WebAPITutorial/ViewModels/HomeIndexViewModel.cs
using System.Collections.Generic;
using WebAPITutorial.Models.Heroes;

namespace WebAPITutorial.ViewModels
{
	public class HomeIndexViewModel
    {
		public IEnumerable<Hero> Heroes
		{
			get; set;
		}
		public string CurrentMessage
		{
			get; set;
		}
	}
}

WebAPITutorial/Controllers/HeroController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAPITutorial.Models;
using WebAPITutorial.Models.Heroes;
using WebAPITutorial.Services;
using WebAPITutorial.ViewModels;

namespace WebAPITutorial.Controllers
{
	//[Route( "[controller]/[action]" )]
	[Authorize] // make sure that the user is authenticated
	public class HeroController : Controller
	{
		private IHeroData _heroData;
		public HeroController( IHeroData heroData ) // require services from the constructor
		{
			_heroData = heroData;
		}
		[AllowAnonymous] // override authorize attribute of this controller
		public IActionResult Index()
		{
			var model = new HomeIndexViewModel();
			model.Heroes = _heroData.GetAll();
			model.CurrentMessage = "Hero Creation Successful!";
			return View( model );
		}

		//[Route( "{id}" )]
		public IActionResult About( int id )
		{
			//var hero = _heroData.GetAll().First( h => h.ID == id );
			var hero = _heroData.Get( id );
			if( hero == null )
			{
				return View( "NotFound" );
			}
			return View( hero );
		}

		[HttpGet] //Get because this is returning the view for the create
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken] // extremely important when you're authenticating users using cookies. This makes sure that the form submitted by the user is indeed the form we gave to the user, not some made-up form by malicious attackers
		public IActionResult Create( HeroEditModel model ) // prevent 'over-posting' by serializing the model to hero object and passing the hero object instead of the model.
		{
			if( ModelState.IsValid )
			{
				var newHero = new Hero
				{
					ID = model.ID,
					Name = model.Name,
					DOB = model.DOB,
					Power = model.Power,
					Type = model.Type
				};
				newHero = _heroData.Add( newHero );

				// To avoid duplicate POST requests, the response to a POST request should be a redirecto to a GET page, in this case,
				// the details page of the newly created hero.
				return RedirectToAction( nameof( About ), new
				{
					id = newHero.ID // this hero's ID is passed in to the url as id param, url/hero/about/{id}
				} );
			}
			else // invalid input model
			{
				return View();
			}


			// this is dangerous because returning a view to a POST request
			// can cause problems when the user refreshes the page. Refreshing a POST page can cause duplicate 
			// transactions, duplicate entries, etc.

			// return View( "About", newHero ); 
			
		}

		public IActionResult Error()
		{
			return View( "NotFound" );
		}
    }
}

WebAPITutorial/Pages/Hello.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAPITutorial.Models.Heroes;
using WebAPITutorial.Services;

namespace WebAPITutorial.Pages
{
	public class HelloModel : PageModel
    {
		private IHeroData _heroData;
		public string Message
		{
			get; set;
		}
		public HelloModel(IHeroData data)
		{
			_heroData = data;
		}
        public void OnGet(int id, string name)
        {
			Message = $"Hello {name} with id {id}";
        }
    }
}

WebAPITutorial/Pages/Heroes/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAPITutorial.Models.Heroes;
using WebAPITutorial.Services;

namespace WebAPITutorial.Pages.Heroes
{
	[Authorize]
	public class EditModel : PageModel
	{
		private IHeroData _heroData;

		[BindProperty] // bind incoming request to this property
		public Hero Hero
		{
			get; set;
		}
		public EditModel(IHeroData heroData)
		{
			_heroData = heroData;
		}
		public IActionResult OnGet(int id)
		{
			Hero = _heroData.Get( id );
			if( Hero == null )
			{
				return RedirectToAction( "Index", "Hero" );
			}
			return Page(); // this is similar to View(). The page to be returned is THIS page, in this case, Edit.cshtml.
		}
		
		public IActionResult OnPost() // name of the HTTP Handlers matteres. OnGet, OnPost, OnPut, etc.
		{
			if( !ModelState.IsValid )
			{
				return RedirectToAction( "Index", "Hero" );
			}
			_heroData.Update( Hero );
			return RedirectToAction( "About", "Hero", new
			{
				id = Hero.ID
			} );
			
		}
	}
}

WebAPITutorial/ViewComponents/HeroViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebAPITutorial.Models.Heroes;
using WebAPITutorial.Services;

namespace WebAPITutorial.ViewComponents
{
	public class HeroViewComponent : ViewComponent
    {
		private IHeroData _heroData;

		public HeroViewComponent(IHeroData heroData)
		{
			_heroData = heroData;
		}

		public IViewComponentResult Invoke()
		{
			var model = new Hero
			{
				Name = "Captain America 3",
				DOB = "1/29/1965",
				Type = HeroType.Science,
				ID = 5,
				Power = "Super Human Strength"
			};
			return View( "Default", model );
		}
    }
}

WebAPITutorial/Pages/Hello.cshtml
@*page directive is an indication of a Razor page*@
@*this page can require para values from the url, in this case, "name". It can be an optional param by adding a question mark*@
@page "{id}/{name}"


@*Model in Razor pages are the code behind class objects for this file.*@
@model HelloModel

<div>@Model.Message</div>

WebAPITutorial/Pages/Heroes/Edit.cshtml
@page "{id}"
@using WebAPITutorial.Pages.Heroes
@model EditModel

@{
}

<h1>Edit Hero</h1>

<form method="post">
	@*2 different ways to bind input to property. Second option is preferred*@
	@*<input type="text" name="name" value="" /> @*the name attribute indicates what this input is for*@

	<input type="hidden" asp-for="Hero.ID" />
	<div>
		<label asp-for="Hero.Name"></label>
		<input asp-for="Hero.Name" />
		<span asp-validation-for="Hero.Name"></span>
	</div> @*this will automatically bind the input value to the name property of the Model*@
	<div>
		<label asp-for="Hero.Type"></label>
		<select asp-for="Hero.Type" asp-items="@Html.GetEnumSelectList<HeroType>()"></select>
		<span asp-validation-for="Hero.Type"></span>
	</div>

	<input type="submit" name="save" value="Save" />
</form>
<div asp-validation-summary="All"></div>

WebAPITutorial/Pages/_Layout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width"/>
	<title>@ViewBag.Title</title>
</head>
<body>
	<div>
		@RenderBody() @*this is like the router outlet + Component selector from Angular. This renders the passed in content*@
	</div>
	<footer>
		@RenderSection( "footer", required: false ) @*the page that will be rendered here needs to use the same name as the render section's name, "footer" in this case*@
		@*@await Component.InvokeAsync("Hero")*@
		<vc:hero></vc:hero>
	</footer>
	<div>
		@DateTime.Now.Year
	</div>
</body>
</html>

WebAPITutorial/Views/Hero/About.cshtml
@model Hero
@{
	ViewBag.Title = Model.Name;
}

<div>
	<h1>Name: @Model.Name</h1>
	<h2>@Model.DOB</h2>
	<h3>ID : @Model.ID</h3>
	<h4>@Model.Power</h4>
	<h5>Type: @Model.Type</h5>
	<a asp-action="Index" asp-controller="Hero">Home</a>@*Go back to Home link. give it the controller name and the action method to look for*@
</div>

WebAPITutorial/Views/Hero/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebAPITutorial/Views/Hero/Create.cshtml
@model Hero
@{
	ViewBag.Title = "Create";
}
<h1>Create Hero</h1>

<form method="post">
	@*2 different ways to bind input to property. Second option is preferred*@
	@*<input type="text" name="name" value="" /> @*the name attribute indicates what this input is for*@
	<div>
		<label asp-for="Name"></label>
		<input asp-for="Name" />
		<span asp-validation-for="Name"></span>
	</div> @*this will automatically bind the input value to the name property of the Model*@
	<div>
		<label asp-for="Type"></label>
		<select asp-for="Type" asp-items="@Html.GetEnumSelectList<HeroType>()"></select>
		<span asp-validation-for="Type"></span>
	</div>

	<input type="submit" name="save" value="Save" />
</form>

<a asp-action="Index" asp-controller="Hero">Home</a>
<div asp-validation-summary="All"></div>

WebAPITutorial/Views/Hero/Index.cshtml
@{
	ViewBag.Title = "Home Page";
}
@model HomeIndexViewModel

@foreach( var hero in Model.Heroes )
{
	@Html.Partial( "_Summary", hero )
}

<div>
	<a asp-action="Create">Add Hero</a>
</div>


@section footer{
	@Model.CurrentMessage
}

WebAPITutorial/Views/Hero/NotFound.cshtml
<h1>OOPS! Something happend!</h1>

WebAPITutorial/Views/Hero/_Summary.cshtml
@model Hero

<section>

	<h1>@Model.Name</h1>
	<div>

	</div>
	<div>
		<a asp-action="About" asp-route-id="@Model.ID">More</a> @*asp-route-id is the key value and hero.ID is the value for the id key to pass in to this link*@
		<a asp-page="/Heroes/Edit" asp-route-id="@Model.ID">Edit</a>
	</div>
</section>

WebAPITutorial/Views/Shared/Components/Hero/Default.cshtml
@model Hero

@{
	
}

<div>
	@Model.Name
</div>

WebAPITutorial/Views/Shared/_Layout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width"/>
	<title>@ViewBag.Title</title>
</head>
<body>
	<div>
		@RenderBody() @*this is like the router outlet + component selector from Angular. This renders the passed in content*@
	</div>
	<footer >
		This only shows up on the pages that initialize the footer :: @RenderSection("footer", required:false) @*the page that will be rendered here needs to use the same name as the render section's name, "footer" in this case*@
	</footer>
	<div>
		This shows up on every page that inherits this layout page :: @await Component.InvokeAsync( "Hero" )
		<vc:hero></vc:hero>
	</div>
	<div>
		From the main layout page :: @DateTime.Now.Year
	</div>
	@{
		if( User.Identity.IsAuthenticated )
		{
			foreach( var id in User.Identities )
			{
				<h3>@id.Name</h3>
				<ul>
					@foreach( var claim in id.Claims )
					{
						<li>@claim.Type - @claim.Value</li>
					}
				</ul>
				
			}
		}
		else
		{
			<div>Who are you</div>
		}
	}
</body>
</html>